services:
  mysql:
    image: mysql:8.0
    container_name: book-store-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: book-store-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
